import Foundation
import Testing
@testable import InfomapKit

/// Engine parity against the reference Python implementation (pip infomap
/// 2.15.1): fixtures in `Fixtures/` are generated by
/// `scripts/generate_golden_fixtures.py` and replayed here through the
/// vendored C++ core — the bindings are verified against the reference,
/// never against themselves.
@Suite struct GoldenPartitionTests {
    struct Fixture: Decodable {
        struct Network: Decodable {
            var bipartiteStartId: Int?
            var links: [[Double]]
            var meta: [String: Int]?
        }

        struct Node: Decodable {
            var id: Int
            var path: [Int]
            var flow: Double
        }

        struct Module: Decodable {
            var path: [Int]
            var flow: Double
            var enterFlow: Double
            var exitFlow: Double
            /// The core's childDegree: direct children *including* leaf
            /// nodes — compared against our childCount + nodes.count.
            var childCount: Int
        }

        struct Expected: Decodable {
            var codelength: Double
            var oneLevelCodelength: Double
            var relativeCodelengthSavings: Double
            var numLevels: Int
            var numTopModules: Int
            var numLeafModules: Int
            var nodes: [Node]
            var modules: [Module]
        }

        var name: String
        var flags: String
        var network: Network
        var expected: Expected
    }

    static func loadFixture(_ name: String) throws -> Fixture {
        let url = try #require(Bundle.module.url(
            forResource: name, withExtension: "json", subdirectory: "Fixtures"
        ))
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    static func network(from fixture: Fixture) -> FlowNetwork {
        var network = FlowNetwork(bipartiteStartID: fixture.network.bipartiteStartId)
        for link in fixture.network.links {
            network.addLink(from: Int(link[0]), to: Int(link[1]), weight: link[2])
        }
        return network
    }

    /// Reference tolerance: same version, same algorithm, but a different
    /// compiler/optimizer than the pip wheel — flows and codelengths must
    /// agree far beyond metric relevance, not necessarily to the last ulp.
    static let tolerance = 1e-9

    static func assertParity(_ partition: Partition, _ expected: Fixture.Expected) {
        #expect(abs(partition.codelength - expected.codelength) < tolerance)
        #expect(abs(partition.oneLevelCodelength - expected.oneLevelCodelength) < tolerance)
        #expect(abs(partition.relativeCodelengthSavings - expected.relativeCodelengthSavings) < tolerance)
        #expect(partition.numLevels == expected.numLevels)
        #expect(partition.numTopModules == expected.numTopModules)
        #expect(partition.numLeafModules == expected.numLeafModules)

        #expect(partition.nodePaths.count == expected.nodes.count)
        for node in expected.nodes {
            let expectedModule = Partition.ModulePath(Array(node.path.dropLast()))
            #expect(partition.nodePaths[node.id] == expectedModule, "node \(node.id) leaf module")
            let flow = partition.nodeFlow[node.id] ?? .nan
            #expect(abs(flow - node.flow) < tolerance, "node \(node.id) flow \(flow) vs \(node.flow)")
        }

        #expect(partition.modules.count == expected.modules.count)
        for module in expected.modules {
            let path = Partition.ModulePath(module.path)
            guard let ours = partition.modules[path] else {
                Issue.record("missing module \(module.path)")
                continue
            }
            #expect(abs(ours.flow - module.flow) < tolerance, "module \(module.path) flow")
            #expect(abs(ours.enterFlow - module.enterFlow) < tolerance, "module \(module.path) enterFlow")
            #expect(abs(ours.exitFlow - module.exitFlow) < tolerance, "module \(module.path) exitFlow")
            // Reference childCount is childDegree (submodules + leaves).
            #expect(ours.childCount + ours.nodes.count == module.childCount, "module \(module.path) children")
        }
    }

    @Test func toyMultilevelParity() async throws {
        let fixture = try Self.loadFixture("toy-multilevel")
        let partition = try await InfomapEngine.shared.run(
            Self.network(from: fixture), options: InfomapOptions(seed: 42, trials: 10)
        )
        Self.assertParity(partition, fixture.expected)
    }

    @Test func planted8MultilevelParity() async throws {
        let fixture = try Self.loadFixture("planted8-multilevel")
        let partition = try await InfomapEngine.shared.run(
            Self.network(from: fixture), options: InfomapOptions(seed: 42, trials: 10)
        )
        Self.assertParity(partition, fixture.expected)
        // The planted structure is the point: 8 top modules, 3 levels.
        #expect(partition.numTopModules == 8)
        #expect(partition.numLevels == 3)
    }

    @Test func planted8TwoLevelParity() async throws {
        let fixture = try Self.loadFixture("planted8-twolevel")
        // 50 trials: at 10 the flat search stops in a platform-sensitive
        // local optimum (see scripts/generate_golden_fixtures.py).
        let partition = try await InfomapEngine.shared.run(
            Self.network(from: fixture),
            options: InfomapOptions(seed: 42, trials: 50, hierarchy: .twoLevel)
        )
        Self.assertParity(partition, fixture.expected)
        #expect(partition.numLevels == 2)
    }

    @Test func directedMultilevelParity() async throws {
        let fixture = try Self.loadFixture("directed-multilevel")
        let partition = try await InfomapEngine.shared.run(
            Self.network(from: fixture),
            options: InfomapOptions(seed: 42, trials: 10, flow: .directed)
        )
        Self.assertParity(partition, fixture.expected)
    }

    @Test func planted8RegularizedParity() async throws {
        let fixture = try Self.loadFixture("planted8-regularized")
        // The golden regularized fixture stays unipartite: the pip reference
        // still carries iliasaz/infomap#1, so fork-fixed bipartite behavior
        // is covered by RegularizedBipartiteTests, not by pip parity.
        #expect(fixture.network.bipartiteStartId == nil)
        var options = InfomapOptions(seed: 42, trials: 10)
        options.regularization = .bayesian(strength: 0.3)
        let partition = try await InfomapEngine.shared.run(Self.network(from: fixture), options: options)
        Self.assertParity(partition, fixture.expected)
    }

    @Test func toyMetaParity() async throws {
        let fixture = try Self.loadFixture("toy-meta")
        let meta = try #require(fixture.network.meta)
        var labels: [Int: Int] = [:]
        for (key, value) in meta {
            labels[try #require(Int(key))] = value
        }
        var options = InfomapOptions(seed: 42, trials: 10)
        options.metadata = .init(labels: labels, rate: 1.0)
        let partition = try await InfomapEngine.shared.run(Self.network(from: fixture), options: options)
        Self.assertParity(partition, fixture.expected)
    }

    @Test func runsAreBitReproducible() async throws {
        let fixture = try Self.loadFixture("planted8-multilevel")
        let network = Self.network(from: fixture)
        let options = InfomapOptions(seed: 42, trials: 10)
        let first = try await InfomapEngine.shared.run(network, options: options)
        let second = try await InfomapEngine().run(network, options: options)
        // Full equality — flows, paths, codelengths — not tolerance.
        #expect(first == second)
    }

    @Test func partitionSurvivesCodableRoundTrip() async throws {
        let fixture = try Self.loadFixture("toy-multilevel")
        let partition = try await InfomapEngine.shared.run(
            Self.network(from: fixture), options: InfomapOptions(seed: 42, trials: 10)
        )
        let decoded = try JSONDecoder().decode(Partition.self, from: JSONEncoder().encode(partition))
        #expect(decoded == partition)
    }

    @Test func danglingAndSentinelMetadataAreRefused() async throws {
        let fixture = try Self.loadFixture("toy-multilevel")
        let network = Self.network(from: fixture)
        // Label for a node with no links: the core would silently ignore it.
        var options = InfomapOptions(seed: 42, trials: 10)
        options.metadata = .init(labels: [999: 1])
        await #expect(throws: InfomapError.self) {
            try await InfomapEngine.shared.run(network, options: options)
        }
        // Category -1 is the core's unlabeled sentinel — it would silently
        // merge with unlabeled nodes.
        options.metadata = .init(labels: [0: -1])
        await #expect(throws: InfomapError.self) {
            try await InfomapEngine.shared.run(network, options: options)
        }
    }

    @Test func runFromCancelledTaskThrowsCancellation() async throws {
        let fixture = try Self.loadFixture("toy-multilevel")
        let network = Self.network(from: fixture)
        let task = Task<Partition, any Error> {
            while !Task.isCancelled { await Task.yield() }
            return try await InfomapEngine.shared.run(network, options: InfomapOptions(seed: 42, trials: 10))
        }
        task.cancel()
        await #expect(throws: CancellationError.self) { try await task.value }
    }

    @Test func danglingBipartiteStartIDIsRefused() async throws {
        // 100 is not a node in the toy network — the core would silently
        // mis-split flow, so the engine must refuse before running.
        let fixture = try Self.loadFixture("toy-multilevel")
        var network = Self.network(from: fixture)
        network.bipartiteStartID = 100
        await #expect(throws: InfomapError.self) {
            try await InfomapEngine.shared.run(network, options: InfomapOptions())
        }
    }
}
